from __future__ import annotations

from models import (
    ImprovementResult, NoveltyResult, PublicationRecommendation, PublicationResult,
    ReproducibilityResult,
)


def review_for_publication(
    novelty: NoveltyResult,
    improvement: ImprovementResult,
    reproducibility: ReproducibilityResult,
) -> PublicationResult:
    composite = (
        novelty.novelty_score * 0.35
        + improvement.overall_quality_score * 0.35
        + reproducibility.reproducibility_score * 0.30
    )

    if composite >= 80:
        recommendation = PublicationRecommendation.ACCEPT
    elif composite >= 65:
        recommendation = PublicationRecommendation.MINOR_REVISION
    elif composite >= 45:
        recommendation = PublicationRecommendation.MAJOR_REVISION
    else:
        recommendation = PublicationRecommendation.REJECT

    major_strengths = novelty.strengths[:2] + (
        ["Structurally complete manuscript covering the expected sections."]
        if improvement.overall_quality_score >= 70 else []
    )
    if not major_strengths:
        major_strengths = ["The manuscript addresses a clearly scoped technical problem."]

    major_weaknesses = novelty.weaknesses[:1] + [
        s for sf in improvement.section_feedback for s in sf.suggestions
        if "Add a clearly labelled" in s
    ][:2]
    if reproducibility.reproducibility_score < 50:
        major_weaknesses.append(
            "Reproducibility details are insufficient for independent verification."
        )
    if not major_weaknesses:
        major_weaknesses = ["No major weaknesses surfaced by automated screening."]

    reviewer_comments = [
        f"Novelty: automated screening estimates a novelty score of {novelty.novelty_score}/100.",
        f"Quality: overall manuscript completeness estimated at {improvement.overall_quality_score}/100.",
        f"Reproducibility: {reproducibility.summary}",
        "Recommendation is generated by heuristic screening and should be treated as a "
        "first-pass triage, not a substitute for expert peer review.",
    ]

    return PublicationResult(
        recommendation=recommendation,
        major_strengths=major_strengths,
        major_weaknesses=major_weaknesses,
        reviewer_comments=reviewer_comments,
    )
