from __future__ import annotations

from models import AnalysisReport


def render_markdown(report: AnalysisReport) -> str:
    n, imp, fut, rep, pub = (
        report.novelty, report.improvement, report.future_scope,
        report.reproducibility, report.publication,
    )

    lines: list[str] = []
    a = lines.append

    a(f"# Research Analysis Report")
    a(f"**File:** {report.filename}  ")
    a(f"**Generated:** {report.generated_at.strftime('%Y-%m-%d %H:%M UTC')}  ")
    a(f"**Publication Recommendation:** {pub.recommendation.value}\n")

    a("## 1. Novelty Analysis")
    a(f"- Novelty score: **{n.novelty_score}/100**")
    a(f"- Innovation score: **{n.innovation_score}/100**")
    a(f"- Confidence score: **{n.confidence_score}/100**\n")
    a("**Strengths**")
    for s in n.strengths:
        a(f"- {s}")
    a("\n**Weaknesses**")
    for w in n.weaknesses:
        a(f"- {w}")
    a(f"\n**Research gap notes:** {n.research_gap_notes}\n")

    a("## 2. Paper Improvement")
    a(f"- Overall quality score: **{imp.overall_quality_score}/100**\n")
    for sf in imp.section_feedback:
        status = "present" if sf.present else "missing"
        a(f"### {sf.section} ({status})")
        for s in sf.suggestions:
            a(f"- {s}")
    a("\n**Missing information**")
    for m in imp.missing_information:
        a(f"- {m}")
    a("\n**General writing suggestions**")
    for w in imp.writing_suggestions:
        a(f"- {w}")

    a("\n## 3. Future Scope")
    for label, items in [
        ("Short-term extensions", fut.short_term),
        ("Medium-term research", fut.medium_term),
        ("Long-term research", fut.long_term),
        ("Industrial applications", fut.industrial_applications),
        ("Startup opportunities", fut.startup_opportunities),
        ("Patent ideas", fut.patent_ideas),
        ("PhD extensions", fut.phd_extensions),
        ("Grant opportunities", fut.grant_opportunities),
    ]:
        a(f"**{label}**")
        for it in items:
            a(f"- {it}")
        a("")

    a("## 4. Reproducibility")
    a(f"- Reproducibility score: **{rep.reproducibility_score}/100**")
    a(f"- {rep.summary}\n")
    a("| Checklist item | Found | Note |")
    a("|---|---|---|")
    for c in rep.checklist:
        a(f"| {c.item} | {'✅' if c.found else '❌'} | {c.note} |")

    a("\n## 5. Publication Review")
    a(f"**Recommendation:** {pub.recommendation.value}\n")
    a("**Major strengths**")
    for s in pub.major_strengths:
        a(f"- {s}")
    a("\n**Major weaknesses**")
    for w in pub.major_weaknesses:
        a(f"- {w}")
    a("\n**Reviewer comments**")
    for c in pub.reviewer_comments:
        a(f"- {c}")

    a("\n---\n*Generated by the AI-Powered Research Novelty & Reproducibility "
      "Analyzer — an Agentic AI pipeline. This report is a heuristic first-pass "
      "screening tool and does not replace expert human peer review.*")

    return "\n".join(lines)
